- lib/pact/consumer_contract/pact_file.rb
- spec/lib/pact/consumer_contract/pact_file_spec.rb
Hi,
I've forked the pact, pact-support and pact_broker-client repository and made the changes on the 'basic_auth' branch for each project and created pull request.
The main changes are:
pass the basic auth option to PactFile open method
* added the basic auth options in dsl 
```ruby
honours_pact_with 'ServiceConsumer' do
pact_uri 'http://pact-broker-url/consumer/ServiceConsumer/latest', {username: 'user', password: 'pass'}
end
```
* when running pact:verify:at['pact_broker_url'] task, currently I just let users to set environment variables PACT_REPO_USERNAME, PACT_REPO_PASSWORD for the basic auth information.  I am not sure whether it's good enough.
pass optional pact_broker_basic_auth in the PublicationTask
```ruby
task.pact_broker_basic_auth =  { username: 'basic_auth_user', password: …
```
> Basic auth

- lib/pact/consumer_contract/consumer_contract.rb
- lib/pact/consumer_contract/query.rb
- lib/pact/logging.rb
- lib/pact/matchers.rb
Was seeing the following warnings using rbenv. Seems require_relative and require don't agree on paths of already loaded files.
```
/usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pact-support-0.4.0/lib/pact/matchers/matchers.rb:19: warning: already initialized constant Pact::Matchers::NO_DIFF_AT_INDEX
/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pact-support-0.4.0/lib/pact/matchers/matchers.rb:19: warning: previous definition of NO_DIFF_AT_INDEX was here
/usr/local/Cellar/rbenv/0.4.0/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pact-support-0.4.0/lib/pact/matchers/matchers.rb:20: warning: already initialized constant Pact::Matchers::DEFAULT_OPTIONS
/usr/local/opt/rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/pact-support-0.4.0/lib/pact/matchers/matchers.rb …
```
> Use require over require_relative to avoid double-loading

- lib/pact/reification.rb
- spec/lib/pact/reification_spec.rb
See https://github.com/bethesque/pact-mock_service/issues/26, we noticed when creating the Array based flexible matchers in the JS DSL, that whilst the provider verification worked, the mock service responded with serialised Ruby, rather than the expected response. e.g.
```
{ items: Object({ json_class: 'Pact::ArrayLike', contents: Object({ a: 'String' }), min: 3 }) }) 
```
It seemed the `ArrayLike` class wasn't being properly reified. The response now looks something like:
```
[{a: 'String'}, {a: 'String'}, {a: 'String'}]
```
Additionally, we'll create a test case in the Mock Service project for this.
> Apply reification to ArrayLike flexible matcher.

- lib/pact/consumer_contract/query_hash.rb
- spec/lib/pact/consumer_contract/query_hash_spec.rb
- spec/lib/pact/consumer_contract/request_spec.rb
When I wrote pact expectation with nested hash query, it did not work as I expected. `Pact::QueryHash` seems not to support nested hash query.
I tried with `Rack::Utils.parse_nested_query` but it breaks current behavior with "double param": `param=a&param=b` should be parsed as `{ param: ['a', 'b'] }` while `Rack::Utils.parse_nested_query` parses as `{ param: 'b' }`.
So I simply treat keys of nested hash with `CGI.parse` manner. It works and seems not to break current behavior.
I tried this patch with my project above and it works.
> Nested `QueryHash`

- spec/support/shared_examples_for_request.rb
RSpec says...
```
WARNING: Using the `raise_error` matcher without providing a specific
error or message risks false positives, since `raise_error` will match
when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`,
potentially allowing the expectation to pass without even executing
the method you are intending to call. Actual error raised was
specific error class or message. This message can be supressed by
setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`.
```
Since the error focused in this example is raised by `Hash#fetch`, specifying `KeyError` looks reasonable here for me.
> `raise_error` should be with specific error

- .travis.yml
ref: https://travis-ci.org/bethesque/pact-support/jobs/115061042
The tins gem which pact-support depends does not support ruby1.9 any more. https://github.com/flori/tins/commit/9ebb625d8a987bd54526006441ff97bc14c30e53
You can also pin tins gem version under 1.7.0, but in my humble option, users of pact-support gem will be more happy with new rubies and new gems than old ones.
> [Proposal] Drop supporting ruby1.9

- lib/pact/reification.rb
- spec/lib/pact/reification_spec.rb
`Pact::Reification.from_term` does nearly the same thing as
`Rack::Utils.build_query` does with extracting Pact's terms.
We should escape query values to follow URI spec.
ref: https://github.com/rack/rack/blob/1.6.4/lib/rack/utils.rb#L180
Without escaping, Pact generates pact file without escaping query and it
causes `URI::InvalidURIError` with "URI must be ascii only" message when
replay the request in `pact:verify`.
P.S. "寿司" means :sushi: in Japanese :yum:
> Escape query string components

- lib/pact/shared/dsl.rb
- spec/lib/pact/shared/dsl_spec.rb
There are cases we just want the instance without any configurations like https://github.com/realestate-com-au/pact/pull/101.
Previously, calling `build` without block raised an error:
```
NoMethodError: private method `binding' called for nil:NilClass
```
> Object supporting DSL can be built without block

- lib/pact/reification.rb
- spec/lib/pact/reification_spec.rb
Hello.
I had added the case of nested `Pact::SomethingLike` when reification.
Please confirm. Thanks.
```ruby
[13] pry(main)> request = Pact::SomethingLike.new(
[13] pry(main)*   {
[13] pry(main)*     a: 'String',
[13] pry(main)*     b: Pact::SomethingLike.new(
[13] pry(main)*       c: 'NestedString'
[13] pry(main)*     )
[13] pry(main)*   }
[13] pry(main)* )
=> #<Pact::SomethingLike:0x007f90139a1460 @contents={:a=>"String", :b=>#<Pact::SomethingLike:0x007f90139a14b0 @contents={:c=>"NestedString"}>}>
[14] pry(main)> Pact::Reification.from_term(request)
=> {:a=>"String", :b=>#<Pact::SomethingLike:0x007f90139a14b0 @contents={:c=>"NestedString"}>}
```
```ruby
[8] pry(main)> request = Pact::SomethingLike.new(
[8] pry(main)*   {
[8] pry(main)*     a: 'String',
[8] pry(main)*     b: …
```
> Supporting nested Pact::SomethingLike reification

- lib/pact/consumer_contract/pact_file.rb
- pact-support.gemspec
- spec/lib/pact/consumer_contract/pact_file_spec.rb
We run pact verification with pact_broker in CI job. Sometimes, pact_broker responds server error and that causes our CI failed. This is annoying for me. I think fetching pact file can be retryable. How about this change?
> Retry reading pact file

- lib/pact/matchers/matchers.rb
- pact-support.gemspec
- spec/spec_helper.rb
This gem shouldn't be included as a production dependency.
> move awesome_print dependency to development

- lib/pact/consumer_contract/interaction.rb
- lib/pact/errors.rb
- spec/lib/pact/consumer_contract/interaction_spec.rb
To ensure they have all necessary data. The lack of data can cause
errors in pact verification.
This is a follow up PR for https://github.com/realestate-com-au/pact/pull/122.
> Enable interactions to validate themselves

- lib/pact/matching_rules/jsonpath.rb
We are using a HAL api that uses colon for namespacing, here is an example:
```
{
"doc:book": "value"
}
```
Matching rules are currently not applied properly because of the colon character, making us unable to verify mocks.
```
"matchingRules": {
"$.doc:book": {
```
I've added this simple fix, it'd be great to get this merged in asap as I have to try to bring this until pact-js.
Note: the path with colon are parsed correctly if they are in a each like matchers.
Food for thoughts: other libraries are using a dot for namespacing, others are using a hash or a dollar sign for json property names (like json schema), which would also break the string scanner regexes.
Another "path format" would need to be supported.
I didn't write a test as this class is apparently not tested.
I was also unable …
> Added colon support to matching rules path.

- pact-support.gemspec
This PR is related to a change in Pact, which led to a failure when used with JRuby 9.1.13.0.
The [gemspec](https://github.com/pact-foundation/pact-support/blob/master/pact-support.gemspec), has pegged fakefs to `0.5.2`:
```
gem.add_development_dependency 'fakefs', '0.5.2' #0.5.3+ breaks everything
```
[FakeFS 0.5.2 code is from 2014](https://github.com/fakefs/fakefs/releases/tag/v0.5.2).
This commit added that line: https://github.com/pact-foundation/pact-support/commit/9bba528bca17c4650eb135fb35b5b23df72feb67
Perhaps a newer fakefs would make things... better? 
https://github.com/fakefs/fakefs/releases/tag/v0.11.2
See https://github.com/realestate-com-au/pact/pull/144
> Gemspec: Try using FakeFS 0.11.2

- README.md
This PR changes the Travis build badge to the one not for the personal repository, but to the one on `pact-foundation`. 
Speculation: this repo was moved and the badge link was not updated.
Hope this helps!
> README: use foundation build badge

- lib/pact/configuration.rb
- lib/pact/consumer_contract/consumer_contract.rb
- lib/pact/consumer_contract/query_string.rb
- lib/pact/matchers/matchers.rb
- lib/pact/matching_rules/jsonpath.rb
- lib/pact/reification.rb
- lib/pact/shared/form_differ.rb
- lib/pact/shared/json_differ.rb
- lib/pact/shared/request.rb
- lib/pact/shared/text_differ.rb
I noticed a number of warnings from this lib when working with a Ruby 2.5 project. When running the tests here, the first thing I noticed is that the test suite cannot be run currently on 2.5 (Fixnum -> Integer change is a big violator, also problems in `spec/lib/pact/consumer_contract/pact_file_spec.rb`).
Anyway, I figured it wouldn't hurt to at least address the warnings that I'm seeing. I went pragmatic on each one, so variable names are pretty week and I'm not 💯 on the circular reference fixes.
Let me know what you think! Thanks 💫
> Fix Ruby 2.5 warnings

- .travis.yml
- pact-support.gemspec
- spec/lib/pact/matchers/list_diff_formatter_spec.rb
- spec/lib/pact/matchers/matchers_messages_mismatched_value_spec.rb
- spec/lib/pact/matchers/matchers_messages_regexp_spec.rb
- spec/lib/pact/matchers/type_difference_spec.rb
- spec/lib/pact/matchers/unix_diff_formatter_spec.rb
- spec/support/ruby_version_helpers.rb
Per discussion in #53, this PR updates the app to build against Ruby 2.5. Unfortunately I don't think there is a clean way to have it build against both 2.3 _and_ 2.5, i.e. I expect the versions < 2.4 to fail at the moment.
If we do want to have the build matrix run against all the listed versions, then we might have to do some version detection in the test suite to tailor its assertions.
Anyway, just starting the conversation here. Hopefully this is helpful!
> Build against Ruby 2.5

- lib/pact/helpers.rb
- spec/lib/pact/helpers_spec.rb
Noticed some irregularities in these files when adding some more [matchers](https://github.com/pact-foundation/pact-js/issues/120#issuecomment-349169195) to pact js.
Also, corrected miliseconds misspelling and created an alias for backwards compatibility - not sure if it's referenced elsewhere so perhaps the alias is unnecessary.
> chore(tests): cleanup helper spec naming

- pact-support.gemspec
Modernise gemspec
- Remove redundant encoding as it is implied with Ruby > 2
- Update homepage reference
- Remove redundant files from gem distribution
> Modernise gemspec

- pact-support.gemspec
I have missed this from https://github.com/pact-foundation/pact-support/pull/72. Sorry 🤦‍♂
> fix: add CHANGELOG to gem distribution

- .gitignore
- lib/pact/consumer_contract/consumer_contract.rb
- lib/pact/consumer_contract/interaction.rb
- lib/pact/consumer_contract/interaction_v2_parser.rb
- lib/pact/consumer_contract/interaction_v3_parser.rb
- spec/lib/pact/consumer_contract/consumer_contract_spec.rb
1) Added a `metadata` attribute to the `Interaction` class to pass metadata at the interaction level.
2) Added a `#writable_interactions` method to `ConsumerContract` which returns the list of contract interactions after filtering out interactions that have `write_to_pact` set to false in their metadata.
> Support marking an interaction as writable/not writable

- spec/lib/pact/matching_rules/v3/extract_spec.rb
- spec/lib/pact/matching_rules/v3/merge_spec.rb
- Use compact class declaration to avoid unneeded deep indentation
- Use compound matchers when possible
- Use `context` instead of `describe` for state
> refactor: clean up Pact v3 specs

- lib/pact/reification.rb
- pact-support.gemspec
* Removing the randexp dependency.
* randexp is removed from pact in this PR - https://github.com/pact-foundation/pact-ruby/pull/202 
* Issue with the randexp is that it overrides the Array's pick method in this file - https://github.com/benburkert/randexp/blob/master/lib/randexp/core_ext/array.rb 
* This is causing issues with other unit tests which we have in our repo.
Testing:
* I have tested pact-support after removing the randexp from requirement and looks fine from my end.
> fix: remove randexp dependency

- lib/pact/matchers/embedded_diff_formatter.rb
- lib/pact/support/version.rb
- lib/tasks/pact.rake
- pact-support.gemspec
- spec/lib/pact/matchers/embedded_diff_formatter_spec.rb
The `term-ansicolor` gem injects a global `Term` module that has a high probability of naming collision for other common class names. This PR replaces that gem with the `rainbow` gem to avoid this issue.
> Benjaminpjacobs:bjacobs/replace-ansicolor-gem

- lib/pact/consumer_contract/interaction_v2_parser.rb
- lib/pact/consumer_contract/pact_file.rb
- lib/pact/matching_rules/merge.rb
- lib/pact/term.rb
```
…/json/add/regexp.rb:17: warning: method redefined; discarding old as_json
…/activesupport-7.0.2.3/lib/active_support/core_ext/object/json.rb:134: warning: previous definition of as_json was here
…/consumer_contract/interaction_v2_parser.rb:41: warning: assigned but unused variable - request
…/matching_rules/merge.rb:45: warning: assigned but unused variable - recursed
…/consumer_contract/pact_file.rb:39: warning: assigned but unused variable - e
…/consumer_contract/pact_file.rb:61: warning: mismatched indentations at 'end' with 'if' at 58
```
> Fixup ruby warnings

- lib/pact/consumer_contract/request.rb
- spec/lib/pact/consumer_contract/request_spec.rb
We want to parse generators part of the contract to support them in the verifier
Based on previous pull request  https://github.com/pact-foundation/pact-support/pull/79, added commit to address feedback
> feat(generators): add generators to a consumer contract request

- lib/pact/configuration.rb
- spec/lib/pact/configuration_spec.rb
see https://github.com/ku1ik/rainbow\?tab\=readme-ov-file\#advanced-usage
preserves original behaviour of outputting color codes on non-tty/dumb terminals which caused failures in checking output when tested in gha via pact-ruby
relates to 
- https://github.com/pact-foundation/pact-support/pull/95
- https://github.com/pact-foundation/pact-ruby/pull/295
- https://github.com/pact-foundation/pact-ruby/pull/254
finally fixes the failure, which led to the revert of the change, and will finally allow us to remove the term-ansicolor dep from pact 👍🏾
> fix: enable color on non-tty if color_enabled

- lib/pact/helpers.rb
- lib/pact/matchers/matchers.rb
- lib/pact/term.rb
- spec/lib/pact/helpers_spec.rb
- spec/lib/pact/matchers/matchers_messages_regexp_spec.rb
- spec/lib/pact/term_spec.rb
- spec/support/ruby_version_helpers.rb
continuation of #38 
fixes #13 by utilising regex string from [pact-jvm](https://github.com/pact-foundation/pact-jvm/blob/master/core/matchers/src/main/kotlin/au/com/dius/pact/core/matchers/MatcherExecutor.kt#L56-L59)
notes from previous PR
- on consumer side, pact.term allowed int and float(decimal) value, with the value changed to a string (which is stored in the pact file)
- on the provider side, int and float(decimal) values returned from the consumer, were not transformed into strings for comparison against the specified term regex.
This updated change will allow int/float(decimal) values to be changed to string at the point of comparison against the regex, both during consumer and provider tests.
On the provider side, if the value is a float or string, the error message returned …
> Lindomar reitz add support to match integers and floats

- lib/pact/matchers/unix_diff_formatter.rb
- lib/pact/shared/jruby_support.rb
- spec/lib/pact/matchers/unix_diff_formatter_spec.rb
json 2.8.0+ no longer prints empty hashs over new lines, so we now get this output
```
Diff
--------------------------------------
Key: - is expected 
+ is actual 
Matching keys and values are not shown
{
-  "thing": {
-    "alligator": {
-      "name": "Mary"
-    }
-  }
+  "thing": {}
}
Description of differences
--------------------------------------
```
compared to the expected
```
Diff
--------------------------------------
Key: - is expected 
+ is actual 
Matching keys and values are not shown
{
"thing": {
-    "alligator": {
-      "name": "Mary"
-    }
}
}
Description of differences
--------------------------------------
generates the right number of lines, even with ActiveSupport loaded
Finished in 0.00154 seconds (files took 0.42989 seconds to load)
1 example, 0 failures
``` …
> fix: add blank lines to empty hashs - json 2.8.x regression

- README.md
- lib/pact/generator/date.rb
- lib/pact/generator/datetime.rb
- lib/pact/generator/provider_state.rb
- lib/pact/generator/random_boolean.rb
- lib/pact/generator/random_decimal.rb
- lib/pact/generator/random_hexadecimal.rb
- lib/pact/generator/random_int.rb
- lib/pact/generator/random_string.rb
- lib/pact/generator/regex.rb
- lib/pact/generator/time.rb
- lib/pact/generator/uuid.rb
- lib/pact/generators.rb
- pact-support.gemspec
- spec/lib/pact/generator/date_spec.rb
- spec/lib/pact/generator/datetime_spec.rb
- spec/lib/pact/generator/provider_state_spec.rb
- spec/lib/pact/generator/random_boolean_spec.rb
- spec/lib/pact/generator/random_decimal_spec.rb
- spec/lib/pact/generator/random_hexadecimal_spec.rb
- spec/lib/pact/generator/random_int_spec.rb
- spec/lib/pact/generator/random_string_spec.rb
- spec/lib/pact/generator/regex_spec.rb
- spec/lib/pact/generator/time_spec.rb
- spec/lib/pact/generator/uuid_spec.rb
- spec/lib/pact/generators_spec.rb
Continuation of https://github.com/pact-foundation/pact-ruby/pull/273
part of https://github.com/pact-foundation/pact-ruby/issues/318
> feat: add v3/v4 generators (thanks @slt)

- lib/pact/shared/active_support_support.rb
- spec/lib/pact/consumer_contract/active_support_support_spec.rb
Seems like the fix introduced in https://github.com/pact-foundation/pact-support/commit/f54a97c93fdaa3bd769b8963e290358143862070 has a couple of issues:
* It doesn't insert the newline for arrays
* It inserts newlines when it finds `{}` or `[]` inside a string in the json document, which makes it an invalid document.
We've ran into the second issue, it's preventing us from upgrading since some of our pipelines fail.
The solution is hacky, it relies on the json being pretty formatted. In that case each line should have a single value, and the `{}` or `[]`, with an extra `,` should be the last content in the line.
```json
{
"empty_array": [],
"other": {
"more": "fields"
},
"empty_hash": {}
}
```
> Fix for generation of invalid json

- .gitignore
- Gemfile
- lib/pact/consumer_contract/consumer_contract.rb
- pact-support.gemspec
- spec/lib/pact/matchers/differ_spec.rb
- spec/support/ssl_server.rb
Changes in the JSON.load are causing downstream deprecation warnings.  
- updated json gem previously not specficied.
- updated rack3 for tests
- fixed spec diffs around position offsets. Perhaps naive but fails in master and current release.
- bumped diff-lcs to latest
> chore: update gems and fix specs.

- lib/pact/consumer_contract/consumer_contract.rb
follow up to yesterdays fixes. uses the safer json load with options.
> fix: use the safe json load to fix deprecation warnings.

- lib/pact/matchers/list_diff_formatter.rb
- pact-support.gemspec
- spec/lib/pact/matchers/list_diff_formatter_spec.rb
Replaced awesome_print dependency and usage with amazing_print across the codebase.
- Updated `pact-support.gemspec` to use `amazing_print` instead of `awesome_print`
- Adjusted formatting in `lib/pact/matchers/list_diff_formatter.rb`
- Updated tests in `spec/lib/pact/matchers/list_diff_formatter_spec.rb` accordingly
> Replace awesome_print with amazing_print #122
